### PR TITLE
Update w/updated email 230104MAY2018

### PR DESCRIPTION
**Pull request by chrisvoncsefalvay**

### CODE REVIEW

**Comment by chrisvoncsefalvay** [comment]
The nomenclature I use to fill this in was:

CONFIRMED:
– cases: “Total des cas confirmes”
– deaths: “Don’t total des deces parmi les cas confirmes”

PROBABLE:
– cases: “total des cas suspects”
– deaths: *empty*, unless otherwise specified in the text – the deaths only differentiate ‘confirmed’, and not between ‘suspected’ vs ‘probable’ deaths

SUSPECTED
– cases: row “total des cas suspects”
– deaths: row “total des deces” minus row “dont total des deces parmi les cas confirmees” (it is assumed that any decedents who are not confirmed are suspected rather than probable

**Comment by chrisvoncsefalvay** [comment]
Noted also in this one:
– 1 case in Bikoro is regarded as a ‘probable’
– 2 negatives in Iboko

**Comment by cmrivers** [comment]
Jinx, we must have been working on it at the same time.

**Comment by chrisvoncsefalvay** [comment]
Hah! :) I'm a night owl, @cmrivers. This is what I do before sleepytime. 

I'll close this PR as it's no longer consistent with the new data schema you implemented (which is WAY better!).

**Pull request closed without merging**
